name: BarterEconomy
version: '${version}'
main: org.fastmcmirror.bartereco.BarterEconomy
api-version: 1.13
authors: [ FlyProject ]
description: Trade with others using your items
softdepend:
  - PlaceholderAPI
commands:
  beco:
    permission: bartereconomy.use
    description: BarterEconomy Command
    aliases:
      - bartereconomy
      - beconomy
      - barter
permissions:
  bartereconomy.use:
    description: Permission
    default: true